apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-4
spec:
  volumes:
    - name: k8-vol-1
      configMap:
        name: k8-cm-1
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: k8-vol-1
          mountPath: /etc/config
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: k8-cm-2
              key: name
      envFrom:
        - configMapRef:
            name: k8-cm-3
