apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-5
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: sec-ctx-demo
      image: busybox:1.28
      securityContext:
        allowPrivilegeEscalation: false
