apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-3
spec:
  volumes:
    - name: k8-vol-1
      secret:
        secretName: k8-sec-1
        defaultMode: 0755
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: k8-vol-1
          mountPath: "/etc/foo"
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: k8-sec-2
            key: key1
      envFrom:
      - secretRef:
          name: k8-sec-3